[theme]
primaryColor = "#087F8C"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EBF1F6"
textColor = "#172B4D"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
